# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180630_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
